[package]
name = "GameOfResources_Backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
actix-files = "0.6.2"
actix-web = "4.4.0"
async-std = "1.12.0"
env_logger = "0.10.1"
tokio = "1.35.1"
